### Day Objectives
    - Packages and modulus
    - Comprehensions
    - Functional Programming
    - Numpy

- Packages and modulus
    - Module --> Collection of functions is called a module
           (or) collection of methods,classes,functions...etc
    
    - We have 2 types of modules
        1.built-in module :-  random,math,print,os.......etc
        2.User defined module:-   Developed by the users
        
  - package:-   collection of modules is called a package
                  - Package has python code

In [1]:
import math

In [6]:
print(math.sqrt(25))
print(math.ceil(7.8))
print(math.floor(7.8))
print(math.pow(2,5))

5.0
8
7
32.0


In [8]:
import random
print(random.randint(100,10000))

3878


In [11]:
from package import module

In [12]:
module.add1(4,5)

9

In [13]:
from package1 import module1

In [14]:
module1.add2(7,8)

15

In [15]:
dir(module)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'add1']

### Comprehensions
    -------------------------------------------------
    - It is a process of creating new sequence from an
       existed sequence

    - Types of comprehensions
    --------------------------------
    - List comprehension
    - Dictionary comprehension
    - Set comprehension
    
    ## Syntax:-    [output_variable loop condition]
    
   - Advantages
   ------------------
   - Less code
   - Less complexity

In [16]:
# list comprehension
li =  [2,6,7,8,12,89]
for i in li:
    if(i%2==1):
        print(i,end=' ')

7 89 

In [18]:
# using list comprehension
g = [i for i in li if(i%2==0)]
print(g)

[2, 6, 8, 12]


In [19]:
# print natural numbers upto 20
n = [i for i in range(20)]
print(n)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [20]:
n = [i**2 for i in range(20)]
print(n)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


In [21]:
# Dictionary Comprehensions
d = {i:i**2 for i in range(1,10)}
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


In [22]:
d = {i:i**3 for i in range(1,10)}
print(d)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729}


In [25]:
d = {3:78,7:90,3:89}
d1 = {i for i in d.values()}
print(d1)

{89, 90}


In [29]:
s1 = {67,44,89,34,90,50,60}
s = set()
for i in s1:
    if(i%10==0):
        s.add(i)
print(s)

{50, 60, 90}


In [30]:
g = {i for i in s1 if(i%10==0)}
print(g)

{50, 60, 90}


### Functional Programming
----------------------------------------
   - It is used to create small functions
   - We can call it as single line functions
   - Anonymous functions
    
    - lambda()
      - syntax:-    lambda arguments:condition
      
    - map()
       - syntax:    map(function,sequence)
    
    - filter()
        - syntax:-   filter(function,sequence)
    

In [31]:
# addition of 2 numbers using functions
def add(a,b):
    return a+b
add(5,6)

11

In [34]:
# using lambda
d = (lambda a,b:a+b)
d(6,7)

13

In [35]:
k = (lambda a,b,c:a*b*c)
k(4,5,6)

120

In [37]:
# map()
def mul(a):
    return a*a
m = map(mul,[1,3,5,8])
print(list(m))

[1, 9, 25, 64]


In [38]:
c = ['raju','ravi','rani']
res = list(map(str.upper,c))
res

['RAJU', 'RAVI', 'RANI']

In [40]:
# filter
d = [45,78,11,89,23,77]
def greater(d):
    if(d>50):
        return True
    else:
        return False
n = filter(greater,d)
for i in n:
    print(i,end=' ')

78 89 77 

##### Introduction to numpy
-------------------------------------
   - Numpy(Numerical python)
   - Numpy is a python library used for working with arrays
   - It is a fundamental package for scientific computing  in python
   - It is used to create multi dimensional arrays
      for fast operations
   - Numpy arrays are stored at one continuous place
      in memory
   - Using numpy we can perform mathematical and logical 
       operations on arrays
       
 - Adavantages
 --------------------------
 - Consumes less memory
 - fast as compared with python lists
 - convinent to use

In [41]:
import numpy

In [42]:
numpy.__version__

'1.24.3'

In [43]:
li = [5,7,8,9,1]
li+8  # element wise addition not possible in the list

TypeError: can only concatenate list (not "int") to list

In [44]:
import numpy as np

In [45]:
np.__version__

'1.24.3'

### Creating arrays
    - array()
       - 0-dimensional array 
       - 1- dimensional aray
       -  2- dimensional array
       -  3- dimensional array

In [48]:
# Numpy methods 
print(len(dir(np)))

598


In [49]:
# 0- Dimensional array
a = np.array(3)
print(a,type(a))

3 <class 'numpy.ndarray'>


In [50]:
# 1- dimensional array
a1 = np.array([1,23,78,90])
print(a1,type(a1))

[ 1 23 78 90] <class 'numpy.ndarray'>


In [51]:
a1+8

array([ 9, 31, 86, 98])

In [52]:
# 2-dimensional array
a3 = np.array([[5,6,7],[7,3,9]])
print(a3,type(a3))

[[5 6 7]
 [7 3 9]] <class 'numpy.ndarray'>


In [54]:
a3

array([[5, 6, 7],
       [7, 3, 9]])

In [57]:
print(a3[0],a3[1])

[5 6 7] [7 3 9]


In [60]:
print(a3[0][1],a3[1][2])

6 9


In [61]:
# 3-dimensional array
a4 = np.array([[34,56,78],[45,22,78],[44,78,11]])
print(a4,type(a4))

[[34 56 78]
 [45 22 78]
 [44 78 11]] <class 'numpy.ndarray'>


In [70]:
# pre defined functions (or) built-in functions in numpy
print(a4)
print(a4.shape) # to get the no of rows and columns
print(a4.ndim)  # To get dimensions
print(a4.size)  # to get the no of elements in array
print(a4.dtype)  # which datatype
print(a4.itemsize) # howmany bytes-- int 4 bytes

[[34 56 78]
 [45 22 78]
 [44 78 11]]
(3, 3)
2
9
int32
4


In [71]:
# conversion of int to complex
b = np.array([5,6,7,3],dtype='complex')
b

array([5.+0.j, 6.+0.j, 7.+0.j, 3.+0.j])

In [72]:
# conversion of int to float values
b = np.array([5,6,7,3],dtype='float')
b

array([5., 6., 7., 3.])

In [74]:
b1 = np.array([5.6,8.9,2.8])
print(b1,type(b1),b1.dtype)

[5.6 8.9 2.8] <class 'numpy.ndarray'> float64


In [82]:
# argmax()--> It prints higest value index
# argmin()--> It prints lowest value index
n = np.array([45,78,11,78,88])
print(n)
print(n.max(),n.min(),n.sum(),n.argmax(),n.argmin())

[45 78 11 78 88]
88 11 300 4 2


In [83]:
# Creating arrays using tuple
k = np.array((45,78,11,78))
print(k,type(k))

[45 78 11 78] <class 'numpy.ndarray'>


In [85]:
# creating array using dictionary
k1 = np.array({2:78,9:67,"a":"b",9:78})
print(k1,type(k1))

{2: 78, 9: 78, 'a': 'b'} <class 'numpy.ndarray'>


In [86]:
# numpy array using range() function
n = np.array(range(10))
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [87]:
n1 = np.array(range(10,30))
print(n1,type(n1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] <class 'numpy.ndarray'>


In [88]:
# range with skip count
n1 = np.array(range(10,30,3))
print(n1,type(n1))

[10 13 16 19 22 25 28] <class 'numpy.ndarray'>


In [4]:
# arange()
import numpy as np
n2 = np.array(np.arange(2.5,9.5))
print(n2)

[2.5 3.5 4.5 5.5 6.5 7.5 8.5]


In [10]:
# range()
import numpy as np
n8 = np.array(range(1,100))
print(n8)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [12]:
# linspace()
c2 = np.linspace(10,20,5)
print(c2)

[10.  12.5 15.  17.5 20. ]


In [13]:
# linspace()
c2 = np.linspace(10,20,5,dtype=int)
print(c2)

[10 12 15 17 20]


In [14]:
# To change the data type
# int to float
h = np.array([4,5,6,1,8],dtype=float)
h

array([4., 5., 6., 1., 8.])

In [15]:
# float to int
h1 = np.array([2.4,6.7,1.8,5.8],dtype=int)
print(h1)

[2 6 1 5]


In [27]:
# Array intialization
# zero's method
a = np.zeros(5)
print(a)
a1 = np.zeros((3,4),dtype=int)
print(a1)

[0. 0. 0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
# one's method
a = np.ones(5)
print(a)
a1 = np.ones((3,4),dtype=int)
print(a1)

[1. 1. 1. 1. 1.]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
a = np.ones(5)
print(a)
a1 = np.ones((3,5),dtype=int)
print(a1)

[1. 1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
# print identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
print(np.eye(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [31]:
# 3,4,5 as diagonal values
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [33]:
# Another method to print identity matrix
n = np.identity(3,dtype=int)
n

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
# diagonal values
np.diag([34,67,89,12,78])

array([[34,  0,  0,  0,  0],
       [ 0, 67,  0,  0,  0],
       [ 0,  0, 89,  0,  0],
       [ 0,  0,  0, 12,  0],
       [ 0,  0,  0,  0, 78]])

In [4]:
# full()
# 1-d array
import numpy as np
print(np.full(4,7))
print(np.full(10,8))
print(np.full(20,6))

[7 7 7 7]
[8 8 8 8 8 8 8 8 8 8]
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


In [8]:
# 2-d array
print(np.full((2,2),3))
print(np.full((3,3),4))

[[3 3]
 [3 3]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [9]:
# modify the values
a = np.full((4,2),3)
print(a)

[[3 3]
 [3 3]
 [3 3]
 [3 3]]


In [12]:
a[1]=7
a[2]=12
print(a)

[[ 3  3]
 [ 7  7]
 [12 12]
 [ 3  3]]


In [13]:
a[2][1]=15
print(a)

[[ 3  3]
 [ 7  7]
 [12 15]
 [ 3  3]]


In [15]:
# 2-d array
li1 = [34,56,78,11]
li2 = [45,78,22,89]
b = np.array([li1,li2])
print(b)
print(b.ndim)  # which dimension

[[34 56 78 11]
 [45 78 22 89]]
2


In [20]:
# Arithmetic Operations
n1 = np.array([[45,67],[3,5]])
print('N1 Matrix is: ')
print(n1)
n2 = np.array([[3,5],[7,8]])
print("N2 Matrix is: ")
print(n2)

N1 Matrix is: 
[[45 67]
 [ 3  5]]
N2 Matrix is: 
[[3 5]
 [7 8]]


In [23]:
print(n1+n2) # Matrix addition
print(n1-n2) # Matrix substraction
print(n1.dot(n2))  # matrix multiplication

[[48 72]
 [10 13]]
[[42 62]
 [-4 -3]]
[[604 761]
 [ 44  55]]


In [ ]:
## Random()
    - It is one of the sub module in numpy
    - It is used to generate random numbers

In [24]:
# Print random methods in numpy
r = np.random
print(dir(r))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'sta

In [30]:
# Generate single random value
print(np.random.randint(1,100))

71


In [34]:
# Generate random numbers between range
print(np.random.randint(1,20,6))

[17  4  4  1 19 10]


In [38]:
# 2-d matrix using random
print(np.random.randint(10,30,(2,3)))

[[24 29 15]
 [20 22 15]]


In [39]:
print(np.random.randint(10,30,(4,4)))

[[21 14 13 23]
 [12 17 10 16]
 [24 24 26 24]
 [19 21 21 22]]


In [44]:
p = np.random.randint(10,30,(3,4))
print(p)
print(p[0])  # 1st row
print(p[-1])  # last row
print(p[::-1])  # reversed matrix

[[16 29 16 22]
 [16 27 28 16]
 [25 28 17 14]]
[16 29 16 22]
[25 28 17 14]
[[25 28 17 14]
 [16 27 28 16]
 [16 29 16 22]]


In [46]:
# Boolean indexing and fancy indexing
print(p)

[[16 29 16 22]
 [16 27 28 16]
 [25 28 17 14]]


In [50]:
print(p>20)

[[False  True False  True]
 [False  True  True False]
 [ True  True False False]]


In [51]:
print(p<20)

[[ True False  True False]
 [ True False False  True]
 [False False  True  True]]


In [52]:
# Print even numbers
print(p%2==0)

[[ True False  True  True]
 [ True False  True  True]
 [False  True False  True]]


In [54]:
# print odd numbers
print(p%2==1)

[[False  True False False]
 [False  True False False]
 [ True False  True False]]


In [55]:
print(p%5==0)

[[False False False False]
 [False False False False]
 [ True False False False]]


In [56]:
# fancy indexing
     # it will return's values
print(p)

[[16 29 16 22]
 [16 27 28 16]
 [25 28 17 14]]


In [59]:
print(p[p%2==0])  # print only even values
print(p[p%2==1])  # print only odd values

[16 16 22 16 28 16 28 14]
[29 27 25 17]


In [ ]:
## Reshape()
    - Based on the elements we can reshape
    - It converts 1-d to n-d array

In [61]:
# 1-d array
n = np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
# 1-d to 2-d array
n = np.arange(10).reshape(2,5)
print(n)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [63]:
# 4-dimensions
n = np.arange(20).reshape(4,5)
print(n)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [64]:
n = np.arange(30).reshape(3,10)
print(n)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [70]:
# resize()
n = np.arange(12).reshape(3,4)
print(n)
print(np.resize(n,(2,2)))
print(np.resize(n,(5,5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [2 3]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11  0]]


In [71]:
# slicing
a = np.random.randint(1,30,(10,3))
print(a)

[[ 7 13 29]
 [23 17  7]
 [11 19 22]
 [19  1  6]
 [12 11  5]
 [21  7 15]
 [ 9 26  8]
 [14  2 15]
 [12 27 17]
 [22 19 21]]


In [72]:
print(a[0:3])

[[ 7 13 29]
 [23 17  7]
 [11 19 22]]


In [73]:
print(a[4:9])

[[12 11  5]
 [21  7 15]
 [ 9 26  8]
 [14  2 15]
 [12 27 17]]


In [77]:
print(a[-1])
print(a[::-1])
print(a[0::2])
print(a[0::4])

[22 19 21]
[[22 19 21]
 [12 27 17]
 [14  2 15]
 [ 9 26  8]
 [21  7 15]
 [12 11  5]
 [19  1  6]
 [11 19 22]
 [23 17  7]
 [ 7 13 29]]
[[ 7 13 29]
 [11 19 22]
 [12 11  5]
 [ 9 26  8]
 [12 27 17]]
[[ 7 13 29]
 [12 11  5]
 [12 27 17]]


In [82]:
# scientific
import numpy as np
print(np.log(2))
print(np.log(5))
print(np.log([28,9,12,78]))

0.6931471805599453
1.6094379124341003
[3.33220451 2.19722458 2.48490665 4.35670883]


In [85]:
# To find exponential values
print(np.exp(3))
print(np.exp(8))
print(np.exp([56,33,78,1,2]))

20.085536923187668
2980.9579870417283
[2.09165950e+24 2.14643580e+14 7.49841700e+33 2.71828183e+00
 7.38905610e+00]


In [87]:
np.sin(0)

0.0

In [88]:
np.tan(30)

-6.405331196646276

In [89]:
np.cos(0)

1.0

 #### Pandas
     - It means panel data
     - It is one of the data science package
     - Used for data manuplation,analysis, and cleaning
     
  - It contains two data structures
      - Series --> Sequence of data
      - Data Frames --> Dataframe is a data with row and column

In [ ]:
# installation
 - pip install pandas

In [90]:
import pandas as pd

In [91]:
pd.__version__

'2.0.3'

In [93]:
# Creation of series using string
s = "hello"
pd.Series(s)

0    hello
dtype: object

In [94]:
s1 = "good evening to all".split()
pd.Series(s1)

0       good
1    evening
2         to
3        all
dtype: object

In [98]:
# using list
li = [4,5,"a","b",7.8,3.7]
j = pd.Series(li)
print(j,type(j))

0      4
1      5
2      a
3      b
4    7.8
5    3.7
dtype: object <class 'pandas.core.series.Series'>


In [96]:
# changing index
li = [4,5,"a"]
pd.Series(li,index=['int','float','str'])

int      4
float    5
str      a
dtype: object

In [97]:
li = [4,5,"a"]
pd.Series(li,index=['v1','v2','v3'])

v1    4
v2    5
v3    a
dtype: object

In [99]:
# Giving indexes and values to the series 
    # data structure using list
li1 = pd.Series([4,5,6,7],index = ['A','B','C','D'])
print(li1)

A    4
B    5
C    6
D    7
dtype: int64


In [100]:
# using dictionary
d = pd.Series({'name':'vanitha','roll no':4857,'branch':'ece'})
print(d)

name       vanitha
roll no       4857
branch         ece
dtype: object


In [101]:
# using tuple
t = pd.Series((56,78,11,45))
t

0    56
1    78
2    11
3    45
dtype: int64

In [103]:
print(t[2],t[3])

11 45


In [105]:
print(d['roll no'],d['name'])

4857 vanitha


In [106]:
print(d)

name       vanitha
roll no       4857
branch         ece
dtype: object


In [107]:
print(li1)

A    4
B    5
C    6
D    7
dtype: int64


In [108]:
# To GET multiple items
print(li1['A':'C'])

A    4
B    5
C    6
dtype: int64


In [109]:
print(li1['A':'D':2])

A    4
C    6
dtype: int64


In [111]:
# UPDATE THE SERIES VALUES
li1['A']=67
li1

A    67
B     5
C     6
D     7
dtype: int64

In [112]:
# using replace method we can change the value
li1 = li1.replace(6,66)
li1

A    67
B     5
C    66
D     7
dtype: int64